---
- name: Setup working directory
  ansible.builtin.include_tasks: setup_working_directory.yml

- name: Check if Vagrantfile exists
  ansible.builtin.stat:
      path: "{{ machine.working_dir }}/Vagrantfile"
  register: Vagrantfile

- name: Run 'vagrant {{ vagrantoptions }}' on host and display output
  ansible.builtin.include_tasks: run_cmd_on_host.yml
  when:
      - vagrantoptions is defined
      - Vagrantfile.stat.exists
