---
- name: "Run 'vagrant {{ vagrantoptions }}' on host and display output"
  block:
      - name: "Run 'vagrant {{ vagrantoptions }}' on host"
        ansible.builtin.shell: "vagrant {{ vagrantoptions }}"
        args:
            chdir: "{{ machine.working_dir }}"
        register: response

      - name: Display run output
        ansible.builtin.debug:
            msg: 
                - "{{ item.stdout_lines | default(item) }}"
        with_items:
            - "{{ response.results | default(response) }}"
        when:
            - item.changed is defined
            - item.changed == true