---
- name: Create working directory if not present
  ansible.builtin.file:
      path: "{{ machine.working_dir }}"
      state: directory
      mode: '0755'

- name: Create Vagrantfile
  template:
      src: Vagrantfile.j2
      dest: "{{ machine.working_dir }}/Vagrantfile"
      mode: '0644'
      force: true

- name: Copy provisioning files to VM host
  copy:
      src: "{{ item }}"
      dest: "{{ machine.working_dir }}"
      mode: '0644'
  loop: "{{ machine.provisioning_files }}"
  when: machine.provisioning_files is defined and machine.provisioning_files | length > 0